### ISSUE TITLE
투표결과 Read API

### ISSUE THREAD

**Issue by junsushin-dev** [Team-Panopticon/TBD-server#30]
모임 정보 API와
투표 정보 API를 가져와서 프론트에서 조립

**Comment by junsushin-dev** [comment]
별도 API 신설 없이
기존 API 들로 대체 가능한지 체크

**Comment by saeeng** [comment]
투표 Read API 에 확정된 날짜 속성을 추가 -

**Comment by saeeng** [comment]
속성명
` confirmedDateType: {
  date: Dayjs;
  meal?: MealType;
};
`
